apiVersion: v1
kind: Secret
metadata:
  name: longhorn-s3google-credentials
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_ENDPOINTS: aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29t

